### ISSUE TITLE
Aktualisierung von date-fns und date-fns-tz auf neue Major-Version

### ISSUE THREAD

**Issue by camueller** [camueller/node-red-contrib-heatpump-tibber-pv#3]
Mit der aktuellen, neuen Major-Version der o.g. Bibliotheken funktioniert der Flow nicht mehr.
Als Work-Around werden in der Flow-Dokumentation die "alten" Versionen installiert.
Trotzdem sollte der Flow natürlich auf die neue Version angepasst werden.

**Comment by deadrabbit87** [comment]
Gibt es hierzu Neuigkeiten? Würde den Flow gerne in meiner NodeRed Instanz von HomeAssistant nutzen, was aber aufgrund der Bibliothken nicht möglich ist.

**Comment by camueller** [comment]
Ich habe vor einiger Zeit die Dokumentation aktualisiert zwecks Installation der Bibliotheken in der korrekten Version:
https://github.com/camueller/node-red-contrib-heatpump-tibber-pv/blob/main/installation.md#installation-ben%C3%B6tigter-bibliotheken

Damit läßt sich der Flow normal nutzen.

Die Umstellung auf die aktuellen Versionen erfolgt im Rahmen eines anderen Umbaus in den kommenden Monaten.

**Comment by camueller** [comment]
Umgesetzt für Folgeprojekt https://github.com/camueller/node-red-contrib-heatpump-dynamic-tariff
