### ISSUE TITLE
WP Stromverbrauch in Abhängigkeit zur Außentemperatur

### ISSUE THREAD

**Issue by mark-sch** [camueller/node-red-contrib-heatpump-tibber-pv#6]
Die Stromaufnahme der Wärmepumpe variiert ja stärker anhand der Außentemperatur, zum einen weil bei kälteten Temperaturen die Heizlast steigt und zugleich die Arbeitszahl der WP abnimmt.

Steht dem Forecast auch eine Außentemperatur des Folgetages zur Verfügung?
Wenn eine Heizlast Berechnung nach DIN TS 12831 gemacht wurde dann weiß ich ja im Vorfeld schon viel über mein Gebäude, d.h. die Heizlast bei Normaußentemperatur und auch die komplette Heizkurve meines Gebäudes. Zusammen mit den Arbeitszahlen/Datenblätter der WP sollte sich der Strombedarf in Abhängigkeit zur Außentemperatur genauer beziffern lassen. Oder eine Auswertung des WP Stromzählers aus vergangenen Tagen in Bezug zur Außentemperatur.

Gibt es hierzu schon Überlegungen/Erfahrungswerte?

**Comment by camueller** [comment]
> Die Stromaufnahme der Wärmepumpe variiert ja stärker anhand der Außentemperatur

Nein, das ist nur bei Inverter-WP s der Fall und die gab es vor 20 Jahren noch nicht. Meine WP zeigt konstant 4 kW, wenn sie läuft.

Die Heizlast ist ja bei der Auslegung der WP berücksichtigt worden, ist es gibt keine Notwendigkeit, dass in der Steuerung selbst zu berücksichtigen. Abgesehen davon dient die Node-RED-Steuerung nur dazu, der WP bestimmte Stunden zu "erlauben" - sie muss nicht einschalten in diesen Stunden. Ob sie einschaltet, entscheidet die eingebaute Steuerung der WP - unter Berücksichtigung der Aussentemperatur.

**Comment by camueller** [comment]
Für die Berechnung der stündlichen Stromkosten wird aktuell eine konstante Leistungsaufnahem der WP und eine feste Anzahl von täglichen Stunden mit Einschaltoption angenommen. Prinzipiell müsste das auch mit einer modulierenden WP funktionieren - der Unterschied zu einer nicht modulierenden WP (wie bei mir) wäre nur, dass die Einschaltoption auch teilweise genutzt werden würde (durch Einschalten mit reduzierter Leistung).

**Comment by mark-sch** [comment]
OK, dann ist der Flow aktuell so ausgelegt dass man hier während der Heizperiode mit der Anzahl der festen Stunden zur Einschaltoption händisch etwas variieren muss? Wenn man das weiß, alles gut.

Vom Kern wird die Heizlast bei Normaußentemeratur ja ohne oder mit wenig Sperrzeit ausgelegt, sonst wäre die WP ja auch gänzlich überdimensioniert. Mit fester Einschaltoption auf eine begrenzte Anzahl von Stunden optimiert man somit händisch auf ein kleineres Temperaturfenster in der die WP arbeiten und die nötige Heizlast erbringen kann.

**Comment by camueller** [comment]
Es ist durchaus möglich, das der Flow für User mit momodulierenden Wärmepumpen noch angepasst werden muss.
